main:
  - identifier: home
    name: home
    url: /
    weight: 1
    params:
      icon: home
social:
  - identifier: github
    name: GitHub
    url: https://github.com/draconacht
    params:
      icon: brand-github
  - identifier: bluesky
    name: Bluesky
    url: https://bsky.app/profile/draconacht.dev
    params:
      icon: brand-twitter
  - identifier: mastodon
    name: Twitter
    url: https://infosec.exchange/@draconacht
    params:
      icon: link
